In [1]:
from sklearn.datasets import load_iris

iris = load_iris()

x=iris.data
y=iris.target

In [2]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                   test_size=0.4,
                                                   random_state=1)

In [4]:
from sklearn.neighbors import KNeighborsClassifier

model= KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [6]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
acc = accuracy_score(y_test,y_pred)
print(f'Accuracy: {acc}')

Accuracy: 0.9833333333333333


In [7]:
data_baru =[[5,5,3,2],
           [2,4,3,5]]

preds=model.predict(data_baru)
preds

array([1, 2])

In [8]:
pred_species = [iris.target_names[p] for p in preds]
print(f'Hasil Prediksi: {pred_species}')

Hasil Prediksi: ['versicolor', 'virginica']


In [9]:
import joblib

joblib.dump(model,'iris_classifier_knn.joblib')

['iris_classifier_knn.joblib']

In [10]:
production_model = joblib.load('iris_classifier_knn.joblib')

In [11]:
import numpy as np
from sklearn import preprocessing

sample_data=np.array([[2.1,-1.9,5.5],
                      [-1.5,2.4,3.5],
                      [0.5,-7.9,5.6],
                      [5.9,2.3,-5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [12]:
sample_data.shape

(4, 3)

In [13]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [14]:
preprocessor=preprocessing.Binarizer(threshold=0.5)
binarised_data=preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [15]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [16]:
preprocessor=preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)
scaled_data=preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [17]:
scaled_data=preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [18]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [19]:
l1_normalised_data=preprocessing.normalize(sample_data,norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

In [20]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [21]:
l2_normalised_data=preprocessing.normalize(sample_data,norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])